# Generated by Django 6.1 on 2026-08-21 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_firmante', models.CharField(max_length=255)),
                ('email_firmante', models.EmailField(max_length=254)),
                ('id_documento_externo', models.CharField(max_length=100)),
                ('pdf_original', models.FileField(upload_to='docs/originales/')),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to='docs/firmados/')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
