# Generated by Django 6.1 on 2026-08-24 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_app', models.CharField(max_length=100, verbose_name='Nombre de la Aplicación')),
                ('system_name', models.SlugField(unique=True, verbose_name='Código del Sistema')),
                ('system_token', models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='System Token (X-System-Token)')),
                ('ip_permitidas', models.TextField(blank=True, help_text='IPs permitidas separadas por comas. Dejar en blanco para permitir cualquier IP.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('rate_limit', models.IntegerField(default=60, help_text='Límite de peticiones por minuto.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Aplicación Autorizada',
                'verbose_name_plural': 'Aplicaciones Autorizadas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
