# Generated by Django 6.1 on 2026-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0002_aplicacionautorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionfirma',
            name='pagina_firma',
            field=models.IntegerField(default=1, verbose_name='Página de Firma'),
        ),
        migrations.AddField(
            model_name='transaccionfirma',
            name='pos_x',
            field=models.FloatField(default=100.0, verbose_name='Coordenada X (puntos PDF)'),
        ),
        migrations.AddField(
            model_name='transaccionfirma',
            name='pos_y',
            field=models.FloatField(default=100.0, verbose_name='Coordenada Y (puntos PDF)'),
        ),
    ]
